### ISSUE TITLE
Consider adding Plot_Type (fixed vs rotational) to Events_extra_xy

### ISSUE THREAD

**Issue by wright13** [jakegross808/pacn-veg-package#29]
I'm thinking we may want to distinguish on the map between fixed and rotational plots. Also, looking at the methods section, I wonder if we should include a simple table with year/cycle, number of fixed plots monitored, number of rotational plots monitored, and number of transects monitored? Or something like that. Not a big deal with two years of data but I think it'd be useful as you add more data cycles.

**Comment by jakegross808** [comment]
Yes definitely want to distinguish fixed and rotation plots on map. "Plot_Type" is in all the main data tables - that's why it wasn't added to _extra, but if that helps to have it in there, it's fine by me. 

I also agree that a small simple listing or table with n() of rotational and fixed sites for both FTPC (plots) and EIPS (transects) makes sense.

**Comment by wright13** [comment]
Ok sounds good. I can add that column and make a table. I also remember thinking that plot type wouldn't be needed in the _extra table, but it'll be useful for mapping.
