### ISSUE TITLE
Adding new table to ReadEIPS function within utils.R

### ISSUE THREAD

**Issue by jakegross808** [jakegross808/pacn-veg-package#31]
I'm trying to add a new table called EIPS_image_pts to `ReadEIPS() ` 

I got the new code in the function and I updated the GetColSpec() code.

However, after committing, pushing, and clean and rebuild when I try to run `ReadEIPS()` it says it `Error in ReadEIPS() : could not find function "ReadEIPS"`

Is there some rebuild step I am missing?

**Comment by wright13** [comment]
Hmm, that's interesting. I feel like I usually get that error when I make a typo in the function name, but it could be something else. I'm available for a screenshare if you want

**Comment by wright13** [comment]
Oh nevermind, I just got the same error from something else and realized that it's because ReadEIPS isn't an exported function (meaning that it's not meant to be seen by users - it's just for internal use inside of other package functions). I'd test it by calling LoadPACNVeg, or if you want to call it by itself you can use pacnvegetation:::ReadEIPS() (notice that it's 3 colons for non-exported functions)

**Comment by jakegross808** [comment]
ah gotcha. Thanks, that will help to troubleshoot!

**Comment by jakegross808** [comment]
Ok the update worked! 
This option will likely be better for mapping EIPS transects `FilterPACNVeg("EIPS_image_pts")`

It contains all image points along a transect (every 100 meters in subalpine and every 200 m in wet forest) including start and end, while the old option `FilterPACNVeg("Events_extra_xy_EIPS")` only contained the starting point and azimuth.

**Comment by jakegross808** [comment]
I haven't merged my branch to main branch though.
